<h2>Attributes Numpy Array</h2>

In [9]:
import numpy as np
arr = np.array([[5,6,7],[8,9,10],[11,12,13],[1,2,3]])
arr

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [ 1,  2,  3]])

<h4>Size<h4>

In [10]:
# size:Total numbers of elements in teh array
arr.size

12

<h4>dtype<h4>

In [11]:
# dtype: Show type of priority data 
# https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.dtypes.html
arr.dtype

dtype('int32')

<h4>shape<h4>

In [12]:
# Shape: Tells you the number of items along each axis
# Return -> Tuple of integers 
# Example : 1D->(cols,) 2D:(rows,cols), 3D:(Height,Width,Length)
arr.shape

(4, 3)

<h4>ndim<h4>

In [13]:
# ndim: tells you the number of axis in the array
arr.ndim

2

<h4>Function Type<h4>

In [14]:
# Function "type" in Numpy, is different that dtype
type(arr) 

numpy.ndarray

<h2>Create Numpy Array<h2>

<h4>Arange<h4>

In [17]:
# arange: create collection of continuous integers
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr = np.arange(start=10,stop=20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
arr = np.arange(start=10,stop=20,step=2)
arr

array([10, 12, 14, 16, 18])

In [22]:
print(arr.dtype)
arr = np.arange(start=10,stop=20,step=1, dtype=np.int8)
print(arr.dtype)

int32
int8


<h4>Zeros<h4>

In [24]:
# https://numpy.org/doc/stable/reference/generated/numpy.zeros.html
arr= np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [27]:
arr= np.zeros(shape=(3,2),dtype=np.int)
arr

array([[0, 0],
       [0, 0],
       [0, 0]])

<h4>Ones<h4>

In [29]:
# Same parameter with zeros
# https://numpy.org/doc/stable/reference/generated/numpy.ones.html
arr= np.ones(5)
arr

array([1., 1., 1., 1., 1.])

<h4>Linspace<h4>

In [37]:
# linsapce:generates values which are equally spaced from each other.
arr= np.linspace(start=5,stop=10,num=5)
arr

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [38]:
arr= np.linspace(start=0,stop=100,num=10,endpoint=False)
arr

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [39]:
arr= np.linspace(start=0,stop=100,num=10,endpoint=True)
arr

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])