In [11]:
import numpy as np
arr = np.array([2,5,7,3,4,6])
arr

array([2, 5, 7, 3, 4, 6])

<h1>Add, Remove and Sort<h1>

<h4>Append<h4>

In [12]:
# np.append():Return matrix with item add
arr = np.append(arr,15)
arr

array([ 2,  5,  7,  3,  4,  6, 15])

In [14]:
# append in list is correct but numpy is incorrect

#python 
l = [1,2,3]
l.append(4) #correct
print(l) 
#numpy
arr.append(20) #incorrect
arr

[1, 2, 3, 4]


AttributeError: 'numpy.ndarray' object has no attribute 'append'

<h4>Delete<h4>

In [15]:
arr

array([ 2,  5,  7,  3,  4,  6, 15])

In [21]:
# delete:Delete element with index
# Return matrix with element delete
np.delete(arr,1)

array([ 2,  7,  3,  4,  6, 15])

In [23]:
# array of index to delete
np.delete(arr,[0,2,3])

array([ 5,  4,  6, 15])

<h4>Sort<h4>

In [19]:
arr

array([ 2,  5,  7,  3,  4,  6, 15])

In [20]:
np.sort(arr)

array([ 2,  3,  4,  5,  6,  7, 15])

In [36]:
#  Order but kick axis
a = np.array([[1,4],[3,1]])
print("A = \n",a)


print("A ordenado =\n", np.sort(a))


print("A ordenado sin ejes =\n", np.sort(a, axis = None))#flatten

A = 
 [[1 4]
 [3 1]]
A ordenado =
 [[1 4]
 [1 3]]
A ordenado sin ejes =
 [1 1 3 4]


In [40]:
# Order specify a field to use when sorting a structured array
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype) # create a structured array
a

array([(b'Arthur', 1.8, 41), (b'Lancelot', 1.9, 38),
       (b'Galahad', 1.7, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [41]:
np.sort(a, order='height') 

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [42]:
np.sort(a, order=['age', 'height'])

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [4]:
# Sort Direct
temp = np.random.randint(1,10, 10)
temp.sort()
temp

array([2, 2, 2, 2, 3, 3, 3, 6, 6, 8])

In [43]:
# Order Desc
temp = np.random.randint(1,10, 10)
temp[::-1].sort()
temp

array([7, 7, 4, 4, 4, 3, 2, 2, 1, 1])

<h1>Reshaping<h1>

In [44]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [45]:
# Function Numpy reshape
np.reshape(arr,(8,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [47]:
np.reshape(arr,(6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
np.reshape(arr,(2,12))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [50]:
# Reshape directly
arr.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [10]:
# Reshape in python list 
l = [1,2,3,4,5,6,7,8]
np.reshape(l,(2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])