### **Overview**

Dear Learner, 

Congratulations, you have studied NumPy all the way through the end of this bootcamp!!! This is the final graded hands-on exercise where you will be accomplishing the below mentioned task.

**Author:** Avantika Podar

In [3]:
import numpy as np

###Task 1:   

Construct a random 3x28x28 NumPy array called *original* to represent an image and then convert this into into a 1x(3x28x28) array called *flat*. This converts it into a single row of pixels. Next, convert this to a 1D array (flatten the array using flat.flatten()). Print shape of all arrays. You may use the random function to generate the array.



In [4]:
# Generate random array
original = np.random.randint(100, size=(3,28,28))

# change dimension to 1x(3x28x28)
flat = original.reshape(1,3,28,28)

# 1D Array
flat = flat.flatten()
flat

array([34, 83, 36, ..., 86, 24, 27])

In [5]:
print(flat.shape)

(2352,)


### Task 2: Print out the following: 
  * dimension of the arrays.
  * memory address of the arrays (pointer).
  * shape of the arrays.
  * data types of the arrays. 




In [17]:
# Generate Array
arr = np.random.randint(10,size=(2,3))
arr

array([[7, 7, 5],
       [3, 1, 2]])

In [18]:
# dimension of the arrays.
arr.ndim

2

In [24]:
# memory address of the arrays (pointer).
import ctypes
arr.ctypes.data_as(ctypes.POINTER(ctypes.c_int16))

In [25]:
# shape of the arrays.
arr.shape

(2, 3)

In [26]:
# data types of the arrays.
arr.dtype

dtype('int32')

### Task 3: 
Construct a new array which is a negative of the *original* array, i.e, all elements are negative of those in the *original* array. Print the new array. Add the original and new arrays. Print the result. 

In [8]:
# Create Original and newArray
original = np.random.randint(low=-10,high=10, size=(10))
newArray = original * -1
print("Original:",original)
print("New Array:",newArray)

Original: [-10   1   5  -8  -2   3  -8  -7   9   2]
New Array: [10 -1 -5  8  2 -3  8  7 -9 -2]


In [9]:
print(original+newArray)

[0 0 0 0 0 0 0 0 0 0]


###Task 4

A 3x28x28 basically means 28x28 matrices repeated three times. How would you access the first 10 elements of the 2nd row of the second 28x28 matrix? Consider the original array for this. Print the elements.

In [6]:
# Create matrix 3x28x28
arr = np.random.randint(100, size=(3,28,28))
print(arr[1,1,:10])

[20 16 44 90 92 95 37 95 61 60]


### Task 5 
A 3x28x28 image means 3 channels of Red, Green, or Blue (Popularly known as RGB image). Each color channel has a height and width, which is 28X28 in this case. The entire picture can represented through this method. Print the shape of the Blue pixel matrix and its first 3 rows.

In [10]:
# Create matrix 3x28x28
imageArr = np.random.randint(100, size=(3,28,28))
#  Print the shape of the Blue pixel matri
print("Shape of Blue Pixel:",imageArr[2].shape)

Shape of Blue Pixel: (28, 28)


In [11]:
# Print first 3 rows
print("3 Row:",imageArr[2,:3])

3 Row: [[75 44 13 78 40 57 28 22 45 18 75 81 17 91 20 46 23  9 95 75 28 56 78  2
  74  1 32  1]
 [69 43 29 81 87 14 95 81 16 89 50 33  6 19 75 75  1 88 76  9 43 66 28 98
  36 17 96 92]
 [53 17  8 49 15 79 32  1  1 51  1 43 45 32 85 23 49 79 21 61 65 43 55 96
  61 12 88 45]]


### Task 6 
Create a 1 dimensional numpy array of the first 50 even numbers. Convert this to a 10x5 numpy array and print its transpose. 

In [12]:
arr = np.arange(start=0,stop=100,step=2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [14]:
# Convert this to a 10x5 numpy array
arr = arr.reshape( (10,5))
arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [63]:
# print its transpose.
print("Transpose: ",np.transpose(arr))

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98]])

### Task 7 
Consider the 10x5 array created in Task 6. Find the mean of each row and column. You may use in built functions or write your own code.

In [64]:
arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [72]:
# ----With built functions---
# Means of Rows
print("Means each Row:",np.mean(arr,axis=1))

# Means of Colums
print("Means each Column:",np.mean(arr,axis=0))

Means each Row: [ 4. 14. 24. 34. 44. 54. 64. 74. 84. 94.]
Means each Column: [45. 47. 49. 51. 53.]


In [78]:
# Own Implementation
def mean(row):
    return np.sum(row)/row.size

# MEANS OF ROWS
meansRow = []
for row in arr:
    meansRow.append(mean(row))

print("Means each Row:", meansRow)

# MEANS OF ROWS
meansColums = []
for colum in np.transpose(arr):
    meansColums.append(mean(colum))
    
print("Means each Colum:", meansColums) 

Means each Row: [4.0, 14.0, 24.0, 34.0, 44.0, 54.0, 64.0, 74.0, 84.0, 94.0]
Means each Colum: [45.0, 47.0, 49.0, 51.0, 53.0]


### Task 8
Can we create a 3x3 array of the first 50 even numbers? Why or why not? What are other values of m and n for which mxn dimension is allowed for 50 elements?

Response: No, beacause the shape 3x3 don't give the result to store 50 numbers, The other values ares all forms in that can descompose the number 50. Below write the all possible values of m and n for 50 numbers. 

In [83]:
arr = np.arange(start=0,stop=100,step=2)
arr.reshape((3,3))
# Yeah is imposible create arr 3x3 for 50 elements

ValueError: cannot reshape array of size 50 into shape (3,3)

In [15]:
# What are other values of m and n for which mxn dimension is allowed for 50 elements?
def valuesToDescompos(value):
    values = []
    for i in range(1,value):
        if value%i==0:
            values.append([i,value//i])
    return values

valuesAllowDescomd = np.array(valuesToDescompos(50))

print("All Values Allow of m and n: \n",valuesAllowDescomd)

All Values Allow of m and n: 
 [[ 1 50]
 [ 2 25]
 [ 5 10]
 [10  5]
 [25  2]]


In [105]:
# Will Check my response
for valuesAllow in valuesAllowDescomd:
    newArr = arr.reshape(tuple(valuesAllow))
    print(newArr)
    print("Sahpe -> ",newArr.shape,end="\n\n")

[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
  48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
  96 98]]
Sahpe ->  (1, 50)

[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
  48]
 [50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
  98]]
Sahpe ->  (2, 25)

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]
Sahpe ->  (5, 10)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]
Sahpe ->  (10, 5)

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]
 [20 22]
 [24 26]
 [28 30]
 [32 34]
 [36 38]
 [40 42]
 [44 46]
 [48 50]
 [52 54]
 [56 58]
 [60 62]
 [64 66]
 [68 70]
 [72 74]
 [76 78]
 [80 82]
 [84 86]
 [88 90]
 [92 94]
 [96 98]]
Sahpe ->  (25, 2)

